<div class="row">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Name</th>
					<th>Username</th>
					<th>Role</th>
					<th>Edit | Delete</th>
				</tr>
			</thead>
			<tbody>
				<?php 
				foreach($this->entries as $entry){
					$role = $this->roles[$entry->getRguid()];
					echo "\n\t\t\t\t<tr>";
					echo "\n\t\t\t\t\t<td>".$entry->getName()."</td>";
					echo "\n\t\t\t\t\t<td>".$entry->getUsername()."</td>";
					echo "\n\t\t\t\t\t<td>".$role."</td>";
					if('c839dea6d26810e52a84925a1259dd9f' != $entry->getRguid()){
						echo "\n\t\t\t\t\t<td><a href='/users/edit/guid/".$entry->getGuid()."'>Edit</a> | <a href='/users/delete/guid/".$entry->getGuid()."'>Delete</a>	</td>";
					} else {
						echo "\n\t\t\t\t\t<td><span class='label label-important'>This account can NOT be deleted</span></td>";
					}
					echo "\n\t\t\t\t</tr>";
				}
				?>
			</tbody>
		</table>
	</div>
</div>