<div class="row">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Customer</th>
					<th>Description</th>
					<th>Date Called</th>
					<th>Assigned To</th>
					<th>Grab Ticket</th>
				</tr>
			</thead>
			<tbody>
			<?php 
			if($this->entries){
				foreach($this->entries as $entry){
					echo "\n\t\t\t\t<tr>";
					echo "\n\t\t\t\t\t<td>".$this->customers[$entry->getCguid()]."</td>";
					echo "\n\t\t\t\t\t<td>".$entry->getDesc()."</td>";
					echo "\n\t\t\t\t\t<td>".$entry->getDatecalled()."</td>";
					echo "\n\t\t\t\t\t<td>".$this->users[$entry->getUguid()]."</td>";
					echo "\n\t\t\t\t\t<td><a class='btn' href='/tickets/grab/guid/".$entry->getGuid()."/><i class='icon-ok icon-white'></i> Grab</a></td>";
					echo "\n\t\t\t\t</tr>";
				}
			} else {
				echo "<tr><td colspan='5'>No entries found.</td></tr>";	
			}
			?>
			</tbody>
		</table>
	</div>
</div>