<div class="row">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Customer</th>
					<th>Description</th>
					<th>Date Called</th>
					<th>Assigned To</th>
				</tr>
			</thead>
			<tbody>
			<?php 
			foreach($this->entries as $entry){
				$customer = $this->customers[$entry->getCguid()];
				if($entry->getUguid()){
					$user = $this->users[$entry->getUguid()];
				} else {
					$user = "Not Assigned";
				}
				echo "\n\t\t\t\t<tr>";
				echo "\n\t\t\t\t\t<td>".$customer."</td>";
				echo "\n\t\t\t\t\t<td>".$entry->getDesc()."</td>";
				echo "\n\t\t\t\t\t<td>".$entry->getDatecalled()."</td>";
				echo "\n\t\t\t\t\t<td>".$user."</td>";
				echo "\n\t\t\t\t</tr>";
			}
			?>
			</tbody>
		</table>
	</div>
</div>