<?php

echo $this->doctype("HTML5");
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>CRM</title>
    <!--  Styles -->
	<link href="/css/bootstrap.css" rel="stylesheet" />
	<link href="/css/bootstrap-responsive.css" rel="stylesheet" />
	<link href="/css/default.css" rel="stylesheet" />
	
	
	<!--  HTML5 shim, for IE6-8 support of HTML5 Elements -->
	<!--[if lt IE 9]
		<script srce="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>
	<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url() ?>">CRM</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url() ?>">Home</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
<?php echo $this->layout()->content; ?>

	</div>
	<footer class="footer">
        <p>Designed and built with all the love in the world <a href="http://twitter.com/twitter" target="_blank">@twitter</a> by <a href="http://twitter.com/mdo" target="_blank">@mdo</a> and <a href="http://twitter.com/fat" target="_blank">@fat</a>.</p>
        <p>Code licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>. Documentation licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
        <p>Icons from <a href="http://glyphicons.com">Glyphicons Free</a>, licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
	</footer>

</body>
</html>