<?php

echo $this->doctype("HTML5");
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>CRM</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Small CRM App based on needs">
    <meta name="author" content="marcusmyers">
    <!--  Styles -->
	<link href="/css/bootstrap.css" rel="stylesheet" />
	<link href="/css/bootstrap-responsive.css" rel="stylesheet" />
	<link href="/css/default.css" rel="stylesheet" />
	
	
	<!--  HTML5 shim, for IE6-8 support of HTML5 Elements -->
	<!--[if lt IE 9]
		<script srce="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>
	<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url() ?>">CRM</a>
          <?php 
          		$auth = Zend_Auth::getInstance();
          		if($auth->hasIdentity()){
          			$location = $_SERVER['REQUEST_URI'];
          			$arrUri = explode("/",$location);
          			/*$budget = "";
          			$rev = "";
          			$export = "";*/
          			$home = "";
          			$search = "";
          			if(sizeof($arrUri) > 2) {
	          			/*switch($arrUri[2]){
	          				case "bud":
	          				case "budedit":
	          					$budget = " active";
	          				break;
	          				case "rev":
	          				case "revedit":
	          					$rev = " active";
	          				break;
	          			}*/
          			} else {
          				$home = " class='active'";
          			}
                echo '<div class="nav-collapse">
                <ul class="nav">
              		<li'.$home.'><a href="<?php echo $this->url() ?>">Home</a></li>
              		<li'.$search.'>Customer</li>
            	</ul>
          		</div><!--/.nav-collapse -->';
          		}
          ?>
        </div>
      </div>
    </div>

    <div class="container">
	<?php echo $this->layout()->content; ?>

	</div>
	<footer class="footer container">
        <p>Designed and built by <a href="http://www.emoxter.com" target="_blank">marcusmyers</a>. &copy; 2012</p>
        <p>Code available at <a href="http://github.com/marcusmyers/zf-crm"><span class="label label-inverse">github</span></a></p>
	</footer>
	<script type="text/javascript" src="/js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/bootstrap-dropdown.js"></script>
	<script type="text/javascript" src="/js/bootstrap-modal.js"></script>
	<script type="text/javascript" src="/js/bootstrap-tooltip.js"></script>
	<script type="text/javascript" src="/js/bootstrap-popover.js"></script>
	<?php echo $this->headScript();?>
</body>
</html>