<?php

echo $this->doctype("HTML5");
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>CRM</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Small CRM App based on needs">
    <meta name="author" content="marcusmyers">
    <!--  Styles -->
    <link type="text/css" href="/css/ui-darkness/jquery-ui-1.8.20.custom.css" rel="stylesheet" />
	<link href="/css/bootstrap.min.css" rel="stylesheet" />
	<link href="/css/bootstrap-responsive.min.css" rel="stylesheet" />
	<link href="/css/default.css" rel="stylesheet" />
	
	
	<!--  HTML5 shim, for IE6-8 support of HTML5 Elements -->
	<!--[if lt IE 9]
		<script srce="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">CRM</a>
          <?php 
          		$auth = Zend_Auth::getInstance();
          		if($auth->hasIdentity()){
          			$identity = $auth->getIdentity();
          			$location = $_SERVER['REQUEST_URI'];
          			$arrUri = explode("/",$location);
          			$home = "";
          			$customer = "";
          			$user = "";
          			$atickets = "";
          			if(sizeof($arrUri) >= 2) {
	          			switch($arrUri[1]){
	          				case "customers":
	          					$customer = " active";
	          				break;
	          				case "users":
	          					$user = " active";
	          				break;
	          				
	          				case "tickets":
	          					$atickets = " active";
	          				break;
	          				
	          				default:
	          					$home = " class='active'";
	          				break;
	          			}
          			} else {
          				$home = " class='active'";
          			}
	                echo '<div class="nav-collapse">
	                <ul class="nav">
	                	<li class="divider-vertical"></li>
	                	<li'.$home.'><a href="/">Home</a></li>
	              		<li class="dropdown'.$customer.'">
	              			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Customer <b class="caret"></b></a>
	              			<ul class="dropdown-menu">
	              				<li><a href="/customers/add">Add</a></li>
	              				<li><a href="/customers">List Customers</a></li>
	              			</ul>
	              		</li>
	              		<li class="dropdown'.$atickets.'">
	              			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Tickets <b class="caret"></b></a>
	              			<ul class="dropdown-menu">
	                			<li><a href="/tickets/assigned">Assigned</a></li>
	                			<li><a href="/tickets">Open Tickets</a></li>
	                			<li><a href="/tickets/print">Print Open Tickets</a></li>
	               			</ul>
	                	</li>';
	                if($identity['role'] === "c839dea6d26810e52a84925a1259dd9f" || $identity['role'] === "72396390b43aa866e4434d2152e9bf2d"){
	                	echo '<li class="divider-vertical"></li>
	                	<li class="dropdown'.$user.'">
	                		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Users <b class="caret"></b></a>
	              			<ul class="dropdown-menu">
	                			<li><a href="/users/add">Add User</a></li>
	                			<li><a href="/users">List Users</a></li>
	                		</ul>
	                	</li>
	                	<li><a href="/customers/labels">Export for Labels</a></li>';
	                }
	            	echo '</ul>
	          		</div><!--/.nav-collapse -->';
	                echo '<ul class="nav pull-right"><li class="divider-vertical"></li><li><a href="/index/logout">Logout</a></li></ul>';
          		}
          ?>
        </div>
      </div>
    </div>

    <div class="container">
	<?php echo $this->layout()->content; ?>

	</div>
	<footer class="footer container">
        <p>Designed and built by <a href="http://www.emoxter.com" target="_blank">marcusmyers</a>. &copy; 2012</p>
        <p>Code available at <a href="http://github.com/marcusmyers/zf-crm"><span class="label label-inverse">github</span></a></p>
	</footer>
	<script type="text/javascript" src="/js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="/js/jquery-ui-1.8.20.custom.min.js"></script>
	<script type="text/javascript" src="/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/bootstrap-dropdown.js"></script>
	<script type="text/javascript" src="/js/bootstrap-modal.js"></script>
	<script type="text/javascript" src="/js/bootstrap-tooltip.js"></script>
	<script type="text/javascript" src="/js/bootstrap-popover.js"></script>
	<?php echo $this->headScript();?>
	<?php 
	$auth = Zend_Auth::getInstance();
	if($auth->hasIdentity()){
		echo "<script>$('.dropdown-toggle').dropdown();</script>";
	}
	?>
</body>
</html>